smiles-columns = [SMILES]
data-path = reactivity_data_bin.csv
output-dir = reactivity_model
target-columns = [Reactivity_bin]
task-type = classification
metrics = [roc, prc, accuracy]
tracking-metric = roc
epochs = 15
class-balance = true
num-replicates = 3
num-workers = 0
batch-size = 64
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
message-hidden-dim = 300
depth = 3
dropout = 0.0
aggregation = norm
aggregation-norm = 100
activation = RELU
ffn-hidden-dim = 300
ffn-num-layers = 1
multiclass-num-classes = 3
atom-ffn-hidden-dim = 300
atom-ffn-num-layers = 1
atom-multiclass-num-classes = 3
bond-ffn-hidden-dim = 300
bond-ffn-num-layers = 1
bond-multiclass-num-classes = 3
atom-constrainer-ffn-hidden-dim = 300
atom-constrainer-ffn-num-layers = 1
bond-constrainer-ffn-hidden-dim = 300
bond-constrainer-ffn-num-layers = 1
v-kl = 0.0
eps = 1e-08
alpha = 0.1
warmup-epochs = 2
init-lr = 0.0001
max-lr = 0.001
final-lr = 0.0001
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
data-seed = 0
