"""Build the self-contained analysis notebook from the reviewable Python sources."""
from pathlib import Path
import nbformat as nbf

HERE = Path(__file__).resolve().parent
cells = []


def md(text):
    cells.append(nbf.v4.new_markdown_cell(text.strip()))


def code(text):
    cells.append(nbf.v4.new_code_cell(text.strip()))


md('''
# Literature topics and Y/N triage decisions

Classify papers from **Full.xlsx** and compare them with papers whose selected decision
column is exactly **Y** in **SELECTED 7000.xlsx**.
The main chart compares **Y (green)** with **N (orange)**, using explicit decisions
from **Full_gpt-5.xlsx / Agent_YN**. Tables show **Before triage**, **After triage (Y)**,
and **After triage (N)** together, with unresolved decisions reported separately.

The four displayed categories are **Chemical synthesis**, **Theory & modeling**,
**Crystal engineering**, and **Functional materials**. Classification uses each paper's
**title and abstract**, plus document-type metadata, not its journal or triage decision.

**Synthesis-inclusive definition:** Chemical synthesis includes the previous synthetic
methods/transformations topic **plus original papers that explicitly report experimental
MOF or coordination-framework preparation**, even when structure or applications are
their main topic. The original primary topic is preserved separately in the audit.
This is a documented change in category scope, not a change to the saved Y/N decisions.

**Review rule: every identified review article is assigned to Theory & modeling**,
regardless of whether it reviews synthesis, crystal engineering, or applications.
This is a user-defined category convention; it does not imply the review conducted
computational research. Reviews are detected from Document Type or explicit
self-descriptions in the title/abstract. Generic mentions of a perspective or recent
advances alone do not trigger this rule. Detection evidence is exported for inspection.

**Interpretation:** these are rough, deterministic topic estimates, **not classifications
generated by an LLM** and not validated expert labels. Overlapping topics receive one
suggested primary category and a review flag. Broader fallback rules classify papers
missed by specific phrases and expose their weak evidence for review. Missing text
remains an explicit exception. The counts include flagged suggestions.
The original main-contribution rules still produce `primary_topic_category`. The
displayed `category` applies the synthesis-inclusive rule afterward. A reported
preparation statement must concern a framework, rather than a molecular product made
with a MOF catalyst, a MOF-derived material alone, or a hypothetical/background example.
The classifier receives title, abstract, and document type only; desired Y/N proportions are never inputs.

**Topic and eligibility are different.** The project's current
[triage rubric](../MOFinder/prompts/abstract_triage.txt) targets traditional solution-phase
MOF synthesis and excludes some real synthesis work, including mechanochemistry,
film-only growth, and post-synthetic-modification-only studies. A synthesis paper can
therefore be N. This notebook uses stored decisions; the current prompt provides context
and does not establish which prompt version produced the historical decisions.

Run all cells in order. This notebook is self-contained: its analysis code is embedded,
and no API key, network service, or companion Python module is needed.
''')
md('''
## 1. Input files and settings

The default inputs are three original workbooks in the MOF project's `14489 paper`
folder. Change `DATA_DIR` if you move them, or put all three beside the notebook.
`gpt-5` is the default triage column; other available decision columns are also summarized.
The notebook only reads the original workbooks. Outputs go into a separate folder.

If packages are missing, uncomment the installation cell below and run it once.
''')
code('# %pip install pandas openpyxl matplotlib nbformat nbclient ipykernel')
code(r'''
from pathlib import Path
from datetime import datetime, timezone
import hashlib
import json
import platform
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

INPUT_NAMES = ['Full.xlsx', 'SELECTED 7000.xlsx', 'Full_gpt-5.xlsx']
INPUT_CANDIDATES = [Path.cwd(), Path.cwd().parent / '14489 paper', Path.cwd() / '14489 paper']
DATA_DIR = next((p for p in INPUT_CANDIDATES if all((p / name).is_file() for name in INPUT_NAMES)),
                Path.cwd().parent / '14489 paper')

BEFORE_PATH = DATA_DIR / 'Full.xlsx'
AFTER_PATH = DATA_DIR / 'SELECTED 7000.xlsx'
DECISION_PATH = DATA_DIR / 'Full_gpt-5.xlsx'
DECISION_COLUMN = 'Agent_YN'
SHEET_NAME = 'Sheet1'
LABEL_COLUMN = 'gpt-5'  # Alternatives: 'gpt-4o-mini', 'ground truth by gpt-5'
# If changing the triage model, also set the corresponding full decision workbook.
PRIOR_TOPICS_PATH = Path.cwd() / 'baseline_v1_topics.csv'
PREVIOUS_TOPICS_PATH = Path.cwd() / 'archive' / 'v3' / 'paper_topics.csv'
PRIMARY_TOPICS_PATH = Path.cwd() / 'archive' / 'v4' / 'paper_topics.csv'

OUTPUT_DIR = Path.cwd() / 'outputs'
OVERRIDE_PATH = Path.cwd() / 'category_overrides.csv'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.max_columns', 12)
print('Before:', BEFORE_PATH)
print('After: ', AFTER_PATH)
print('Explicit Y/N:', DECISION_PATH, '/', DECISION_COLUMN)
print('After-triage rule:', LABEL_COLUMN, '== Y (case-insensitive; whitespace trimmed)')
print('Output:', OUTPUT_DIR)
''')
md('''
## 2. Read records, match papers, and check labels

**Counting unit:** the main table counts unique papers by normalized DOI, with WOS ID
and then normalized title as fallbacks when DOI is absent. The row-count table preserves
the original spreadsheet counts. Duplicate DOI records are retained in row exports;
their longest available title/abstract record represents the paper for classification.

Selected papers match the before set by DOI, then WOS ID, then an unambiguous title.
Conflicting identifiers are reported rather than silently merged. For duplicate records,
a paper is retained if **any** of its rows has the requested Y label; conflicting decisions
are reported. No download flag, numeric label, citation flag, or blank cell is treated as Y.
''')
code((HERE / 'triage_analysis.py').read_text(encoding='utf-8'))
code('''
before_rows = read_records(BEFORE_PATH, SHEET_NAME)
after_rows = read_records(AFTER_PATH, SHEET_NAME)
decision_rows = read_records(DECISION_PATH, SHEET_NAME)
decision_rows = match_after_to_before(before_rows, decision_rows)
if LABEL_COLUMN not in after_rows:
    raise ValueError('Missing LABEL_COLUMN. Available triage columns: ' +
                     repr([c for c in TRIAGE_COLUMNS if c in after_rows]))
after_rows = match_after_to_before(before_rows, after_rows)
after_rows['selected_Y'] = is_y(after_rows[LABEL_COLUMN])
after_y_rows = after_rows.loc[after_rows.selected_Y].copy()

coverage = pd.DataFrame([
    {'Dataset': name, 'Spreadsheet rows': len(frame), 'Unique papers': frame.paper_id.nunique(),
     'Extra duplicate rows': len(frame) - frame.paper_id.nunique(),
     'Missing title': frame['Article Title'].map(normalize_text).eq('').sum(),
     'Missing abstract': frame['Abstract'].map(normalize_text).eq('').sum(),
     'Missing DOI': frame.doi_key.eq('').sum()}
    for name, frame in [('Before: Full', before_rows), ('Selected: all rows', after_rows),
                        ('After: ' + LABEL_COLUMN + '=Y', after_y_rows)]
])
display(coverage)
print('Actual label counts (different label groups may share duplicate paper IDs):')
display(label_inventory(after_rows))
display(after_rows.groupby(['match_method', 'matched_to_before'], dropna=False).size().rename('Rows').to_frame())

labels_normalized = after_rows[LABEL_COLUMN].str.strip().str.upper()
label_conflicts = after_rows.assign(normalized_decision=labels_normalized).groupby('paper_id').normalized_decision.agg(
    lambda s: '; '.join(sorted(set(s) - {''})))
label_conflicts = label_conflicts.loc[label_conflicts.str.contains(';', regex=False)].reset_index()
print('Papers with conflicting nonblank decisions:', len(label_conflicts))
if len(label_conflicts):
    display(label_conflicts.head(20))
unmatched_y = after_y_rows.loc[~after_y_rows.matched_to_before.astype(bool)]
print('Y rows not safely matched to Full:', len(unmatched_y))
if len(unmatched_y):
    display(unmatched_y[['excel_row', 'DOI', 'Article Title', 'match_method', 'match_issue']].head(20))
print('Explicit full-corpus decisions:')
display(label_inventory(decision_rows, [DECISION_COLUMN]))
print('Unmatched decision records:', int((~decision_rows.matched_to_before.astype(bool)).sum()))
''')
md('''
## 3. Topic rubric and transparent classifier

| Display category | Assignment rule |
|---|---|
| Chemical synthesis | Synthetic routes, molecular/ligand synthesis, or post-synthetic transformations as before; also original papers explicitly reporting experimental MOF/coordination-framework preparation, including synthesis-and-characterization and synthesis-and-application reports. |
| Theory & modeling | All identified review articles (priority rule), plus original work with computational/theoretical methods, simulation, modeling, or prediction as the central topic. |
| Crystal engineering | Structural characterization, topology, packing, polymorphism, and assembly without an explicit framework-preparation statement qualifying for the synthesis-inclusive group. |
| Functional materials | Applications or properties without an explicit framework-preparation statement qualifying for the synthesis-inclusive group, including use of a MOF catalyst to make molecular products. |

For the preserved primary topic, titles receive more weight than abstracts. Distinct phrase groups contribute capped
scores, so repeating a word does not increase its score indefinitely. Specific application
evidence should outweigh a routine mention of synthesis; auxiliary DFT should not
automatically make an experimental application paper theoretical. MOF/material/crystal
mentions alone are weak evidence. Broader lexical fallback assignments are explicitly
flagged as low confidence and retain their matching terms; any unsupported domain
default is separately marked. No triage label is used to choose a topic.

The original primary-topic category and scores remain available. The broader display
assignment has a separate reason and the exact framework-preparation evidence. Reviews
retain their priority rule. Computational, background, hypothetical, and negated
preparation claims do not establish experimental framework synthesis. Missing abstract
evidence does not prove synthesis was absent from the full paper.

The rules below expose their phrases, scores, selection logic, and review criteria.
**Scores and margins are heuristic evidence strengths, not calibrated probabilities.**
The four topics overlap, and this automatic procedure does not fully understand a paper's
main contribution. The review queue and editable overrides are part of the workflow.
''')
classifier = (HERE / 'topic_classifier.py').read_text(encoding='utf-8')
classifier = classifier.split('if __name__ ==')[0].rstrip()
code(classifier)
code('''
# Classify the before set once, then reuse its categories for matched selected papers.
before_papers = unique_papers(before_rows)
unmatched_after = after_rows.loc[~after_rows.matched_to_before.astype(bool)].copy()
paper_pool = pd.concat([before_papers, unique_papers(unmatched_after)], ignore_index=True)
paper_pool = paper_pool.drop_duplicates('paper_id').reset_index(drop=True)
annotations = []
for i, (title, abstract, document_type) in enumerate(zip(paper_pool['Article Title'], paper_pool['Abstract'], paper_pool['Document Type']), start=1):
    annotations.append(classify_topic(title, abstract, document_type))
    if i % 3000 == 0:
        print('Classified {:,} / {:,} unique papers'.format(i, len(paper_pool)))
classified = pd.concat([paper_pool, pd.DataFrame(annotations)], axis=1)
classified = apply_overrides(classified, OVERRIDE_PATH, CATEGORIES)

before_classified = attach_classification(before_rows, classified)
after_classified = attach_classification(after_rows, classified)
after_y_classified = after_classified.loc[after_classified.selected_Y].copy()
assert before_classified.category.notna().all()
assert after_classified.category.notna().all()
assert classified.paper_id.is_unique
assert set(classified.category).issubset(set(CATEGORIES) | {'Unclassified'})
print('Classified {:,} distinct papers; {:,} currently flagged for review.'.format(
    len(classified), classified.review_needed.sum()))
full_paper_decisions = attach_full_decisions(
    before_classified.drop_duplicates('paper_id'), decision_rows, DECISION_COLUMN)
explicit_y_ids = set(full_paper_decisions.loc[full_paper_decisions.triage_decision.eq('Y'), 'paper_id'])
selected_y_ids = set(after_y_classified.paper_id)
if explicit_y_ids != selected_y_ids:
    raise ValueError('The full decision workbook Y set differs from SELECTED 7000 / LABEL_COLUMN. '
                     'Check that both settings refer to the same triage model.')
print('Verified: explicit full-corpus Y decisions equal the selected Y paper set.')
review_articles = full_paper_decisions.loc[full_paper_decisions.is_review_article].copy()
print('Review articles assigned to Theory & modeling:', len(review_articles))
display(review_articles.triage_decision.value_counts().rename('Review articles').to_frame())
''')
md('''
## 4. Before triage, retained (Y), and excluded (N)

**Y and N are separate groups.** The earlier before-triage bars included retained papers;
they were not N bars. The new chart uses explicit decisions, with no category or decision
changed to produce a desired bar pattern. Unknown or conflicting decisions are reported
separately and never silently treated as N.

The summary counts **unique papers** in all three columns. **Before = Y + N** when
there are no Unknown or Conflict decisions. N comes from the explicit full decision
workbook; it is never inferred from absence in the selected workbook. Review columns
show how many rough classifications still need inspection. The row table projects
canonical decisions onto the original full-corpus rows to reconcile with Excel.
''')
code('''
yn_counts = count_yn(full_paper_decisions, CATEGORIES)
print('UNIQUE PAPERS: explicit Y/N decisions')
display(yn_counts)
primary_topic_decisions = full_paper_decisions.copy()
primary_topic_decisions['category'] = primary_topic_decisions.primary_topic_category
primary_topic_counts = count_yn(primary_topic_decisions, CATEGORIES)
taxonomy_transitions = pd.crosstab(full_paper_decisions.primary_topic_category,
                                  full_paper_decisions.category).reindex(
    index=list(CATEGORIES), columns=list(CATEGORIES), fill_value=0)
taxonomy_transitions.index.name = 'Original primary topic'
taxonomy_reassignments = full_paper_decisions.loc[full_paper_decisions.taxonomy_reassigned,
    ['paper_id', 'DOI', 'Article Title', 'primary_topic_category', 'category',
     'framework_synthesis_evidence', 'reassignment_reason', 'triage_decision',
     'review_needed', 'review_reason']].copy()
print('Papers included in Chemical synthesis by explicit framework-preparation evidence:',
      len(taxonomy_reassignments))
print('Original primary topics are preserved in the audit and primary_topic_counts.csv.')
synthesis_summary = full_paper_decisions.groupby('category').agg(
    Papers=('paper_id', 'size'),
    Papers_with_synthesis_evidence=('has_experimental_synthesis', 'sum'))
synthesis_summary = synthesis_summary.reindex(list(CATEGORIES) + ['Unclassified'], fill_value=0)
synthesis_summary['Synthesis evidence (%)'] = (
    100 * synthesis_summary.Papers_with_synthesis_evidence / synthesis_summary.Papers.replace(0, float('nan'))).round(1)
synthesis_summary.index.name = 'Category'
print('INDEPENDENT METHOD TAG: experimental synthesis evidence in title/abstract')
display(synthesis_summary)

category_changes = pd.DataFrame(columns=['paper_id', 'category_v1', 'category_current'])
method_comparison = pd.DataFrame()
if PRIOR_TOPICS_PATH.exists():
    prior = pd.read_csv(PRIOR_TOPICS_PATH, dtype=str, keep_default_na=False)
    if not prior.paper_id.is_unique:
        raise ValueError('Prior category snapshot must have unique paper IDs.')
    category_changes = prior[['paper_id', 'category']].rename(columns={'category': 'category_v1'}).merge(
        classified[['paper_id', 'Article Title', 'category', 'primary_topic_category', 'classification_reason', 'review_needed']],
        on='paper_id', how='inner', validate='one_to_one').rename(columns={'category': 'category_current'})
    method_comparison = pd.crosstab(category_changes.category_v1, category_changes.category_current,
                                    margins=True, margins_name='TOTAL')
    category_changes = category_changes.loc[category_changes.category_v1.ne(category_changes.category_current)]
    print('Papers reassigned by the revised method:', len(category_changes))
    display(method_comparison)

is_subset = bool(after_y_classified.matched_to_before.all())
counts_by_category = count_categories(before_classified, after_y_classified, CATEGORIES,
                                     unique=True, subset=is_subset, full_decisions=full_paper_decisions)
row_counts_by_category = count_categories(before_classified, after_y_classified, CATEGORIES,
                                         unique=False, subset=False, full_decisions=full_paper_decisions)
print('UNIQUE PAPERS — after column:', LABEL_COLUMN)
display(counts_by_category[['Before triage', 'After triage (Y)', 'After triage (N)']])
display(counts_by_category)
print('SPREADSHEET ROWS — includes duplicate records')
display(row_counts_by_category)
if not is_subset:
    print('Retention percentages omitted: some Y papers did not safely match the before corpus.')

# Sensitivity table: all actual decision columns, with the same fixed topic assignments.
label_comparison = []
for col in TRIAGE_COLUMNS:
    if col in after_classified:
        selected = after_classified.loc[is_y(after_classified[col])]
        table = count_categories(before_classified, selected, CATEGORIES, unique=True,
                                 subset=bool(selected.matched_to_before.all()))
        label_comparison.append(table[['After triage (Y)']].rename(columns={'After triage (Y)': col + ' Y'}))
label_comparison = pd.concat(label_comparison, axis=1)
print('UNIQUE Y PAPERS BY DECISION COLUMN — blanks are excluded')
display(label_comparison)
''')
code('''
plot_counts = yn_counts.loc[list(CATEGORIES)]
plt.rcParams.update({'font.size': 11, 'axes.spines.top': False, 'axes.spines.right': False})
fig, ax = plt.subplots(figsize=(10.8, 5.8))
x = list(range(len(plot_counts)))
width = 0.30
b1 = ax.barh([v - width/2 for v in x], plot_counts['N'], height=width,
            label='N', color='#efbd6d', edgecolor='#d2a45b', linewidth=0.5)
b2 = ax.barh([v + width/2 for v in x], plot_counts['Y'], height=width,
            label='Y', color='#8fbd83', edgecolor='#76a66a', linewidth=0.5)
for bars in [b1, b2]:
    ax.bar_label(bars, labels=['{:,}'.format(int(b.get_width())) for b in bars], padding=5, fontsize=10)
ax.set_yticks(x)
ax.set_yticklabels(plot_counts.index)
ax.invert_yaxis()
ax.set_xlabel('Unique papers')
ax.set_title('Literature triage by synthesis-inclusive category', loc='left', weight='bold', pad=18)
ax.set_xlim(0, max(1, plot_counts[['Y', 'N']].to_numpy().max()) * 1.14)
ax.legend(frameon=False, ncol=2, loc='upper right')
ax.xaxis.grid(True, alpha=0.18)
ax.set_axisbelow(True)
unclassified = yn_counts.loc['Unclassified']
unresolved = int(yn_counts.loc['TOTAL', ['Unknown', 'Conflict']].sum())
fig.text(0.02, 0.065, 'Actual decisions: Full_gpt-5.xlsx / Agent_YN. Topic rules v' + CLASSIFIER_VERSION + '; review flags included.',
         fontsize=8.5, color='#52606d')
fig.text(0.02, 0.025, 'Outside the four bars: unclassified Y={:,}, N={:,}; unknown/conflicting decisions={:,}.'.format(
    int(unclassified.Y), int(unclassified.N), unresolved), fontsize=8.5, color='#52606d')
fig.tight_layout(rect=[0, 0.10, 1, 1])
fig.savefig(OUTPUT_DIR / 'triage_Y_N_by_topic.png', dpi=240, bbox_inches='tight')
fig.savefig(OUTPUT_DIR / 'triage_Y_N_by_topic.pdf', bbox_inches='tight')
# Keep the previous chart filenames as aliases for the revised main plot.
fig.savefig(OUTPUT_DIR / 'before_after_topics.png', dpi=240, bbox_inches='tight')
fig.savefig(OUTPUT_DIR / 'before_after_topics.pdf', bbox_inches='tight')
plt.show()
''')
md('''
## 5. Inspect individual papers and correct categories

The next cell displays a reproducible sample from every category and the first flagged
papers. Use the exported audit table to inspect **every paper**, including the title,
abstract, category scores, matched topic evidence, and review reason.

To correct classifications, copy any rows from `outputs/review_queue.csv` (or
`outputs/all_unique_papers.csv`) into `category_overrides.csv` beside the notebook.
Keep `paper_id`; fill a `manual_category` column with an exact category name from the
rubric, and optionally add `review_note`. Extra columns are accepted; blank edits are
ignored. A manual category marks that paper reviewed. Re-run from Section 3 to update
both before and after counts together. Do not edit `automatic_category` or the raw files.
''')
code('''
inspection_columns = ['paper_id', 'Article Title', 'category', 'primary_topic_category',
                      'classification_reason', 'framework_synthesis_evidence',
                      'review_needed', 'review_reason', 'evidence']
sample = pd.concat([group.sample(n=min(3, len(group)), random_state=42)
                    for _, group in classified.groupby('category')])
display(sample[inspection_columns])
review_queue = classified.loc[classified.review_needed].copy()
review_queue['manual_category'] = ''
review_queue = review_queue.sort_values(['category', 'paper_id'])
print('Review queue:', len(review_queue), 'unique papers')
display(review_queue[inspection_columns].head(15))

# Change PAPER_QUERY to part of a title or DOI to inspect particular papers.
PAPER_QUERY = ''
if PAPER_QUERY:
    matches = classified['Article Title'].str.contains(PAPER_QUERY, case=False, regex=False) | classified['DOI'].str.contains(PAPER_QUERY, case=False, regex=False)
    display(classified.loc[matches, inspection_columns + ['Abstract']])
''')
md('''
## 6. Export results and verify totals

`all_unique_papers.csv` and `paper_topic_audit.xlsx` contain the complete classifications.
`doi_classification.csv` is the compact two-column DOI/classification list. The companion
`doi_classification_triage.csv` adds the existing Y/N decision and review flag.
`resolved_unclassified.csv` traces every previously unclassified paper to its new
category, matching evidence, and review reason.
`taxonomy_reassignments.csv` records the synthesis-inclusive reassignments and exact
preparation evidence. `primary_topic_counts.csv` preserves the previous main-topic
counts, and `taxonomy_transition_counts.csv` reconciles the two category definitions.
`before_classified.csv`, `after_all_classified.csv`, and `after_Y_classified.csv` preserve
source rows. The Excel audit also includes the counts, label comparison, duplicate
records, review queue, unmatched Y records, and conflicting decisions. The manifest
records input hashes, chosen label, row and paper counts, and the classification method.
No workbook content is sent to an external service.
''')
code('''
duplicate_rows = pd.concat([
    before_classified.loc[before_classified.paper_id.duplicated(keep=False)].assign(dataset='before'),
    after_classified.loc[after_classified.paper_id.duplicated(keep=False)].assign(dataset='selected')
], ignore_index=True)
before_ids = set(before_rows.paper_id)
after_y_ids = set(after_y_rows.paper_id)
classified['in_before'] = classified.paper_id.isin(before_ids)
classified['after_selected_Y'] = classified.paper_id.isin(after_y_ids)
classified['triage_decision'] = classified.paper_id.map(full_paper_decisions.set_index('paper_id').triage_decision).fillna('Unknown')

doi_classification = full_paper_decisions[['doi_key', 'category']].rename(
    columns={'doi_key': 'DOI', 'category': 'Classification'}).sort_values('DOI')
if doi_classification.DOI.eq('').any() or doi_classification.DOI.duplicated().any():
    raise ValueError('The compact DOI export requires one nonempty DOI per paper.')
doi_classification_triage = full_paper_decisions[
    ['doi_key', 'category', 'triage_decision', 'review_needed']].rename(columns={
        'doi_key': 'DOI', 'category': 'Classification', 'triage_decision': 'Triage decision',
        'review_needed': 'Needs review'}).sort_values('DOI')
resolved_unclassified = pd.DataFrame()
if PREVIOUS_TOPICS_PATH.exists():
    previous = pd.read_csv(PREVIOUS_TOPICS_PATH, dtype=str, keep_default_na=False)
    previous_ids = set(previous.loc[previous.category.eq('Unclassified'), 'paper_id'])
    resolved_unclassified = full_paper_decisions.loc[
        full_paper_decisions.paper_id.isin(previous_ids),
        ['paper_id', 'DOI', 'Article Title', 'category', 'triage_decision',
         'primary_topic_category', 'classification_reason', 'review_needed', 'review_reason', 'evidence']].copy()
    resolved_unclassified['previous_category'] = 'Unclassified'
    print('Previously unclassified papers assigned a topic:',
          int(resolved_unclassified.category.ne('Unclassified').sum()), '/', len(previous_ids))

if PRIMARY_TOPICS_PATH.exists():
    prior_primary = pd.read_csv(PRIMARY_TOPICS_PATH, dtype=str, keep_default_na=False).set_index('paper_id')
    current = full_paper_decisions.set_index('paper_id')
    assert prior_primary.index.is_unique and set(prior_primary.index) == set(current.index)
    current = current.loc[prior_primary.index]
    assert current.primary_topic_category.eq(prior_primary.category).all(), 'Original primary topic changed'
    assert current.triage_decision.eq(prior_primary.triage_decision).all(), 'Saved triage decision changed'
    print('Verified: every original primary topic and saved Y/N decision is preserved.')

tables = {
    'primary_topic_counts': primary_topic_counts.reset_index(),
    'taxonomy_transition_counts': taxonomy_transitions.reset_index(),
    'taxonomy_reassignments': taxonomy_reassignments,
    'doi_classification': doi_classification,
    'doi_classification_triage': doi_classification_triage,
    'resolved_unclassified': resolved_unclassified,
    'Y_N_counts_by_topic': yn_counts.reset_index(),
    'synthesis_evidence_by_topic': synthesis_summary.reset_index(),
    'category_changes_since_v1': category_changes,
    'method_transition_counts': method_comparison.reset_index(),
    'full_decision_audit': full_paper_decisions,
    'review_articles': review_articles,
    'counts_by_category': counts_by_category.reset_index(),
    'row_counts_by_category': row_counts_by_category.reset_index(),
    'label_comparison': label_comparison.reset_index(),
    'coverage': coverage,
    'label_inventory': label_inventory(after_rows),
    'all_unique_papers': classified,
    'before_classified': before_classified,
    'after_all_classified': after_classified,
    'after_Y_classified': after_y_classified,
    'review_queue': review_queue,
    'duplicate_records': duplicate_rows,
    'unmatched_Y': unmatched_y,
    'conflicting_decisions': label_conflicts,
}
for name, table in tables.items():
    table.to_csv(OUTPUT_DIR / (name + '.csv'), index=False, encoding='utf-8-sig')

# The compact workbook carries complete unique-paper results and selected-row results.
workbook_tables = {k: v for k, v in tables.items() if k not in ['before_classified', 'after_all_classified']}
# Stream rows to disk: large abstract/evidence tables need not live as Excel cells in memory.
from openpyxl import Workbook
from openpyxl.cell import WriteOnlyCell
from openpyxl.utils import get_column_letter
workbook = Workbook(write_only=True)
for name, table in workbook_tables.items():
    sheet = workbook.create_sheet(title=name[:31])
    sheet.freeze_panes = 'A2'
    sheet.auto_filter.ref = 'A1:{}{}'.format(get_column_letter(len(table.columns)), len(table) + 1)
    sheet.append(list(table.columns))
    for values in table.itertuples(index=False, name=None):
        excel_row = []
        for value in values:
            value = None if pd.isna(value) else value
            cell = WriteOnlyCell(sheet, value=value)
            if isinstance(value, str):
                cell.data_type = 's'
            excel_row.append(cell)
        sheet.append(excel_row)
workbook.save(OUTPUT_DIR / 'paper_topic_audit.xlsx')

manifest = {
    'run_time_utc': datetime.now(timezone.utc).isoformat(),
    'inputs': {str(p): hashlib.sha256(p.read_bytes()).hexdigest() for p in [BEFORE_PATH, AFTER_PATH, DECISION_PATH]},
    'sheet': SHEET_NAME,
    'label_column': LABEL_COLUMN,
    'YN_source': str(DECISION_PATH),
    'YN_column': DECISION_COLUMN,
    'explicit_Y_unique': int(yn_counts.loc['TOTAL', 'Y']),
    'explicit_N_unique': int(yn_counts.loc['TOTAL', 'N']),
    'unresolved_decisions': int(yn_counts.loc['TOTAL', ['Unknown', 'Conflict']].sum()),
    'classifier_uses_triage_decisions': False,
    'review_article_policy': 'All identified review articles are assigned to Theory & modeling',
    'identified_review_articles': len(review_articles),
    'review_article_detection': 'Document Type, or explicit title/abstract self-description; evidence exported',
    'main_chart': 'Disjoint explicit Y (green) and N (orange); not before-versus-after',
    'label_rule': 'stripped case-insensitive exact Y; any Y per duplicate paper ID',
    'classification': 'Rough deterministic synthesis-inclusive grouping; preserved original main topic plus explicit experimental framework preparation; not generated by an LLM',
    'taxonomy_policy': 'synthesis-inclusive-v1',
    'taxonomy_reassigned_unique': int(classified.taxonomy_reassigned.sum()),
    'framework_synthesis_evidence_unique': int(classified.has_framework_synthesis.sum()),
    'primary_topic_preserved': True,
    'classification_generated_by_llm': False,
    'classifier_version': CLASSIFIER_VERSION,
    'classification_validated_against_expert_labels': False,
    'unique_identity': 'normalized DOI, else WOS ID, else normalized title, else source row',
    'before_rows': len(before_rows),
    'before_unique_papers': before_rows.paper_id.nunique(),
    'after_Y_rows': len(after_y_rows),
    'after_Y_unique_papers': after_y_rows.paper_id.nunique(),
    'unmatched_Y_rows': len(unmatched_y),
    'unique_papers_needing_review': int(classified.review_needed.sum()),
    'fallback_assignments': int(classified.fallback_used.sum()),
    'fallback_basis_counts': classified.loc[classified.fallback_used, 'fallback_basis'].value_counts().to_dict(),
    'unclassified_unique_papers': int(full_paper_decisions.category.eq('Unclassified').sum()),
    'previously_unclassified_papers': len(resolved_unclassified),
    'previously_unclassified_resolved': int(resolved_unclassified.category.ne('Unclassified').sum()) if len(resolved_unclassified) else 0,
    'partition_check': 'Before = explicit Y + explicit N + Unknown + Conflict, at DOI and source-row levels',
    'manual_overrides_applied': int(classified.manual_reviewed.sum()),
    'override_sha256': hashlib.sha256(OVERRIDE_PATH.read_bytes()).hexdigest() if OVERRIDE_PATH.exists() else None,
    'python': platform.python_version(),
    'pandas': pd.__version__,
}
(OUTPUT_DIR / 'run_manifest.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')
assert counts_by_category.loc['TOTAL', 'Before triage'] == before_rows.paper_id.nunique()
assert counts_by_category.loc['TOTAL', 'After triage (Y)'] == after_y_rows.paper_id.nunique()
assert row_counts_by_category.loc['TOTAL', 'Before triage'] == len(before_rows)
assert row_counts_by_category.loc['TOTAL', 'After triage (Y)'] == len(after_y_rows)
print('Verified totals. Results saved to:', OUTPUT_DIR.resolve())
display(counts_by_category[['Before triage', 'After triage (Y)', 'After triage (N)']])
print('Compact DOI classification list (full list is saved as doi_classification.csv):')
display(doi_classification.head(12))
''')

md('''
## 7. Compare four topic definitions and check the requested Y:N ratios

Each definition below assigns a topic from the same title, abstract, and document type.
The alternatives change the meaning of a category; they are not validated improvements
in classification accuracy. All identified reviews remain **Theory & modeling**.
Every paper is included under every definition, including **Unclassified** papers.
Existing manual category corrections, if present, are retained across definitions.

The requested checks are **Chemical synthesis >= 4:1**, **Crystal engineering > 6:1**
(with a separate **> 7:1** check), and **Functional materials Y > N**.
These checks summarize outcomes after classification; they do not determine topic
assignments or select a preferred definition. Moving an N paper requires the same
positive topic evidence that would move a Y paper. No additional rule is fitted to
make the displayed ratios pass.

The four criteria were specified before calculating their comparison results. They
are exploratory choices made with knowledge of the requested targets, not a
preregistered or independently validated classification study. Expert review of a
sample blinded to triage labels is needed to decide which definition best matches
the intended scientific categories.
''')
# Embed source without its sibling-module import: the classifier is already above.
import ast
criteria_source = (HERE / 'topic_criteria.py').read_text(encoding='utf-8')
source_lines = criteria_source.splitlines()
for node in reversed(ast.parse(criteria_source).body):
    if isinstance(node, ast.ImportFrom) and node.module == 'topic_classifier':
        del source_lines[node.lineno - 1:node.end_lineno]
code('\n'.join(source_lines))
code((HERE / 'criteria_analysis.py').read_text(encoding='utf-8'))
code((HERE / 'run_criteria_comparison.py').read_text(encoding='utf-8'))

nb = nbf.v4.new_notebook(cells=cells)
nb.metadata.kernelspec = {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}
nb.metadata.language_info = {'name': 'python', 'version': '3.8'}
nbf.validate(nb)
target = HERE / 'literature_triage_topics.ipynb'
nbf.write(nb, target)
print(target)
